const rocket = [
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4), simple shading (1)", url: "https://f2.toyhou.se/file/f2-toyhou-se/images/94291974_O3DZs98lznaBdjG.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=320913">benjeep</a>', points: "fullbody (4)", url: "https://f2.toyhou.se/file/f2-toyhou-se/images/95964663_HoDUxxWOH0hX2x5.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "base | fullbody (2), simple shading (1)", url: "https://f2.toyhou.se/file/f2-toyhou-se/images/95964515_CykLtckCkvJ4Vuo.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "base | fullbody (2), simple shading (1)", url: "https://f2.toyhou.se/file/f2-toyhou-se/images/95964524_n8inMSlFEkzxraX.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "base | fullbody (2), simple shading (1)", url: "https://f2.toyhou.se/file/f2-toyhou-se/images/95964540_g1pqnkcv8xYGF1i.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=1488">Folktale</a>', points: "fullbody (4)", url: "img/art/rocket/folkrocket.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4), complex shading (3), complex background (3)", url: "https://www.chickensmoothie.com/oekaki/image/image.php?id=1164090&size=large&format=auto&rev=1347121048"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=88963">Soph6297</a>', points: "headshot (1)", url: "https://www.chickensmoothie.com/oekaki/image/image.php?id=1167662&size=large&format=png&rev=1347304029"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=172796">Birchwood Hollow</a>', points: "fullbody (4), complex shading (3), complex background (3)", url: "img/art/rocket/rocketbirch.png"},
  { artist: 'base by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=133150">Cloud-Wolf</a>', points: "base | fullbody(2), simple shading (1)", url: "https://www.chickensmoothie.com/oekaki/image/image.php?id=1206776&size=large&format=png&rev=1349701309"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=208602">abhorsen</a>', points: "base | fullbody (2)", url: "img/art/rocket/rocketabhorsen.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=208602">abhorsen</a>', points: "base | fullbody (2)", url: "img/art/rocket/rocketabhorsen2.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=56916">corgie</a>', points: "base | fullbody (2)", url: "img/art/rocket/rocketcorgie.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=172796">Birchwood Hollow</a>', points: "base | fullbody (2)", url: "img/art/rocket/rocketbirch2.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=56224">KittyCatKita</a>', points: "headshot (1)", url: "https://www.chickensmoothie.com/oekaki/image/image.php?id=1286138&size=large&format=png&rev=1354371996"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=56224">KittyCatKita</a>, ft Lord Dravin', points: "fullbody (4)", url: "https://www.chickensmoothie.com/oekaki/image/image.php?id=1306859&size=large&format=png&rev=1355615105"},
  { artist: 'by legendhasit', points: "fullbody (4), simple background (1)", url: "https://www.chickensmoothie.com/oekaki/image/image.php?id=1304526&size=large&format=auto&rev=1356199185"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=49611">RainbowFinch</a>', points: "base | fullbody (2)", url: "img/art/rocket/rocketrainbowfinch.png"},
  { artist: 'base by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=6094">horsy1050</a>', points: "base | fullbody (2)", url: "https://www.chickensmoothie.com/oekaki/image/image.php?id=1766479&size=large&format=png&rev=1385909034"},
  { artist: 'by Raxacorico', points: "fullbody (4)", url: "img/art/rocket/rocketrax.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=26705">Nikki6Ashba</a>', points: "headshot (1)", url: "img/art/rocket/rocketnikki.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=219096">Tealea</a>', points: "base | fullbody (2)", url: "img/art/rocket/rockettealea.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=172796">Birchwood Hollow</a>', points: "fullbody (4)", url: "img/art/rocket/rocketbirch3.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=56916">corgie</a>', points: "fullbody (4)", url: "img/art/rocket/rocketcorgie2.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=286270">Charchar2</a>', points: "base | fullbody (2)", url: "img/art/rocket/rocketchar.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=87607">iShame</a>', points: "base | fullbody (2)", url: "img/art/rocket/rocketshame.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "base | headshot (1), simple shading (1)", url: "https://flyteck.cfw.me/files/wme/wmehssmrocket.png"},
  { artist: 'by Raxacorico', points: "fullbody (4)", url: "img/art/rocket/rocketrax2.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=26047">BoxLlama</a>', points: "base | fullbody (2), simple animation (1)", url: "img/art/rocket/rocketBoxLlamaAva.gif"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4), simple shading (1)", url: "img/art/rocket/Rocket.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>, ft Soliloquy', points: "fullbody (4), detailed shading (3)", url: "img/art/rocket/Rocket+Sol.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=17125">Sayna Jaye</a>', points: "headshot (1), halfbody (2)", url: "img/art/rocket/RocketBannerSayna.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=54715">~Trompy</a>', points: "fullbody (4)", url: "img/art/rocket/RocketChibiTrompy.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4), simple shading (1)", url: "img/art/rocket/RocketDrawing.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4), simple shading (1)", url: "img/art/rocket/Rocketfb.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "headshot (1)", url: "img/art/rocket/RocketHeadshot3.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=233249">pond.</a>', points: "base | headshot (1)", url: "img/art/rocket/RocketHeadshotCookie.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "headshot (1), complex shading (3)", url: "img/art/rocket/RocketHS2SM.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "headshot (1), complex shading (3)", url: "img/art/rocket/RocketHSSM.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "headshot (1), simple shading (1)", url: "img/art/rocket/RocketIcon.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=61206">Lilian Nightshade</a>, ft Keiran', points: "headshot (1), complex shading (3)", url: "img/art/rocket/RocketLillianRT.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4)", url: "img/art/rocket/RocketPixel.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4)", url: "img/art/rocket/RocketPixel2.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4), simple shading (1)", url: "img/art/rocket/rocketpixel3.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4)", url: "img/art/rocket/RocketPixelLarge.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4), complex shading (3)", url: "img/art/rocket/RocketThingy.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4)", url: "img/art/rocket/rockettiny.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4), simple shading (1)", url: "img/art/rocket/RocketTrad1.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4), simple shading (1)", url: "img/art/rocket/RocketTrad2.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (4), simple shading (1)", url: "img/art/rocket/RocketTradDerp.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "headshot (1), simple shading (1)", url: "img/art/rocket/RocketTradHS.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "headshot (1)", url: "img/art/rocket/WinterHeadshot2.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a> ,ft Estella and Classical', points: "fullbody (4), complex shading (3)", url: "img/art/rocket/AprilFoolsERC.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=233249">pond., ft Soliloquy</a>', points: "base | fullbody (2), complex background (2)", url: "img/art/rocket/RocketSolCookie.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=540499">Shadowhunter,</a>, ft lots', points: "fullbody (4)", url: "img/art/herd/ArtByShadow.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>, ft lots', points: "fullbody (4), simple shading (1)", url: "img/art/herd/TradWMEGroupSm.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>, ft lots', points: "fullbody (4), simple shading (1)", url: "img/art/herd/HerdPicChibi.png"},
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>, ft Honolulu & Ladybird', points: "fullbody (4)", url: "img/art/herd/MyHerd.png"},
];

const honolulu = [
  { artist: 'by <a href="https://www.chickensmoothie.com/Forum/memberlist.php?mode=viewprofile&u=227202">flyteck</a>', points: "fullbody (3), simple shading (1)", url: "img/art/honolulu/hanafb.png"}
];

const ladybird = [
];